import 'package:rinf/rinf.dart';
import 'src/bindings/bindings.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'app.dart';
// import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:firebase_core/firebase_core.dart'; // until we run flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // TODO: Run 'flutterfire configure' to generate firebase_options.dart
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  await Firebase.initializeApp(
      options: FirebaseOptions(
          apiKey: 'AIzaSyB12iWKLtQnrGwH62HfSB5Lb3h6aAdIP2Y',
          appId: '1:902980237738:web:c80288efef81521a2393d3',
          messagingSenderId: '902980237738',
          projectId: 'vibe-language-learning',
          authDomain: "vibe-language-learning.firebaseapp.com",
          storageBucket: "vibe-language-learning.firebasestorage.app",
          measurementId: "G-8FY4SD6PZJ")); // until we run flutterfire configure

  // Initialize Rinf
  await initializeRust(assignRustSignal);

  runApp(
    const ProviderScope(
      child: VibeApp(),
    ),
  );
}
